drop table stock;
drop table user_portfolio;
drop table portfolio;
drop table tf_user;

create table if not exists tf_user (
	uid varchar(255) primary key
);

create table if not exists portfolio (
	pid integer primary key generated by default as identity,
	pname varchar(255)
);

create table if not exists user_portfolio (
	uid varchar(255) references tf_user,
	pid integer references portfolio (pid)
);

create table if not exists stock (
	pid integer references portfolio (pid),
	ticker varchar(255),
	buy_date timestamp,
	sell_date timestamp, 
	quantity integer,
	primary key(pid, ticker, buy_date, sell_date)
);

commit;