drop table stock;
drop table portfolio;
drop table tf_user;

create table if not exists tf_user (
	uid varchar(255) primary key
);

create table if not exists portfolio (
	pid integer primary key generated by default as identity,
	pname varchar(255),
	uid varchar(255) references tf_user(uid)
);

CREATE TABLE IF NOT EXISTS stock (
    uid VARCHAR(255) NOT NULL,
    pid INTEGER NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    buy_date TIMESTAMP,
    sell_date TIMESTAMP, 
    quantity INTEGER,
    PRIMARY KEY (uid, pid, ticker),
    FOREIGN KEY (uid, pid) REFERENCES portfolio (uid, pid)
);

commit;